image: node:20

pages:
  stage: deploy
  script:
    - npm ci
    - npm run build
    - npm i -g staticrypt
    - test -n "$RUNBOOK_PWD"

    - |
      find dist/runbooks -type f -path '*/full/index.html' | while read -r file; do
        echo "Encrypting: $file"
        tmp="${file}.encrypted"
        staticrypt "$file" -p "$RUNBOOK_PWD" --short -o "$tmp"
        test -f "$tmp"
        mv "$tmp" "$file"
        grep -q "staticrypt" "$file"
      done

    - rm -rf public
    - mkdir -p public
    - cp -R dist/* public/

  artifacts:
    paths:
      - public

  only:
    - master
